In [1]:
file_path = "C:\\Users\\Dell\\Downloads\\07. Advertising.csv"

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(file_path)

In [4]:
df.head()

   Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [5]:
df.iloc[:, 1:]

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [6]:
df = df.iloc[:, 1:]

In [7]:
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [8]:
df.isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [9]:
df.shape

(200, 4)

In [10]:
df.dtypes

TV           float64
Radio        float64
Newspaper    float64
Sales        float64
dtype: object

In [11]:
df.duplicated().sum()

0

In [12]:
df.corr()

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

In [13]:
df.describe()

               TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [14]:
X = df.drop('Sales', axis=1)

In [15]:
X.head()

      TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [16]:
y = df.Sales

In [17]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ...
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=45)

In [20]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((160, 3), (40, 3), (160,), (40,))

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
scl = StandardScaler()

In [23]:
x_train_scl = scl.fit_transform(x_train)
x_test_scl = scl.transform(x_test)

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
lr = LinearRegression()

In [26]:
lr.fit(x_train_scl,y_train)

LinearRegression()

In [27]:
lr.coef_

array([ 4.07686894,  2.76432822, -0.10958854])

In [28]:
lr.intercept_

13.87125

In [29]:
y_pred = lr.predict(x_test_scl)

In [30]:
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score

In [31]:
mean_squared_error(y_test,y_pred)

2.256494247280935

In [32]:
mean_absolute_error(y_test,y_pred)

1.0788802763848646

In [33]:
r2_score(y_test,y_pred)

0.8955882331233612

In [34]:
from sklearn.linear_model import Lasso, Ridge, ElasticNet

In [35]:
ls = Lasso()

In [36]:
ls.fit(x_train_scl,y_train)

Lasso()

In [37]:
ls.predict(x_test)

C:\Users\Dell\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2820: UserWarning: X has feature names, but Lasso was fitted without feature names
  warnings.warn(

array([601.78531239, 156.55937294, 687.14827661, 761.79578614,
       842.58266556, 332.44770669, 620.56822711, 300.49646902,
       561.47798305, 138.22364546, 198.14266365, 199.71963848,
       553.36340374, 880.45228307, 790.1495782 , 199.85453046,
       591.00166608, 221.72542783, 770.40226404, 210.73463996,
       761.24234518, 111.03123721, 930.62357063, 484.83162508,
       662.8963939 , 231.00453222, 820.23243475, 560.24285841,
       513.17489326, 565.77059417, 862.08773401, 801.13316681,
       860.84614346, 545.68252983, 407.39290506, 285.64269291,
       500.3323474 , 922.19227142, 598.75405622, 840.55499554])

In [38]:
ls.score(x_test_scl,y_test)

0.8236670415610957

In [39]:
rd = Ridge()

In [40]:
rd.fit(x_train_scl,y_train)

Ridge()

In [41]:
rd.score(x_test_scl,y_test)

0.8962555330609423

In [42]:
Es= ElasticNet()

In [43]:
Es.fit(x_train_scl,y_train)

ElasticNet()

In [44]:
Es.score(x_test_scl,y_test)

0.7490238769673027